# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk-node-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/project

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "editor/package.json" }}--{{ checksum "editor/shadow-cljs.edn"}}

      - run:
          command: npm install;
          working_directory: ~/project/editor

      - run:
          command: npx webpack -p;
          working_directory: ~/project/editor

      - run:
          command: npx shadow-cljs release live trusted bootstrap --verbose;
          working_directory: ~/project/editor

      - run:
          command: npm run deploy;
          working_directory: ~/project/editor

      - run:
          command: cat target/shadow-cljs/shadow-cljs.log.0 2> /dev/null
          working_directory: ~/project/editor
          when: on_fail

      - save_cache:
          paths:
            - ~/project/editor/node_modules
            - ~/project/editor/target
            - ~/.m2
          key: v3-dependencies-{{ checksum "editor/package.json" }}--{{ checksum "editor/shadow-cljs.edn"}}


